package org.example.lesson14.andersenlab;// Generated by Selenium IDE

import org.example.BaseTest;
import org.example.lesson14.pages.HomePage;
import org.junit.jupiter.api.Test;

public class PageObjectCheckFirstCustomerPage extends BaseTest {

    @Test
    public void checkCustomerPage() {
        page.getPage(HomePage.class)
                .GivenIAmAtHomePage()
                .AndCheckingContent()
                .AndOpenCustomerPage()
                .AndCheckIntroText()
                .checkCustomerPageWebElementsPresent();
    }
}
