package org.example.lesson14.andersenlab;// Generated by Selenium IDE

import io.qameta.allure.Description;
import io.qameta.allure.Epic;
import io.qameta.allure.Severity;
import io.qameta.allure.SeverityLevel;
import org.example.BaseTest;
import org.example.lesson14.pages.HomePage;
import org.junit.jupiter.api.Test;

@Epic("Allure examples")
public class PageObjectPageStructureTest extends BaseTest {
    @Test
    @Description("Check home page structure")
    public void checkPageStructure() {
        page.getPage(HomePage.class)
                .GivenIAmAtHomePage()
                .AndCheckHeaderPresent()
                .AndCheckIntroPresent()
                .AndCheckContentPresent()
                .AndCheckFooterPresent()
                .AndCheckCopyrightPresent();
    }

    @Test
    @Description("Check home page header structure")
    public void checkHeaderStructure() {
        page.getPage(HomePage.class)
                .GivenIAmAtHomePage()
                .AndCheckingHeader()
                .AndCheckBookACallPresent()
                .AndCheckHeaderMenuPresent();
    }

    @Test
    @Description("Check home page content structure")
    @Severity(SeverityLevel.CRITICAL)
    public void checkContentStructure() {
        page.getPage(HomePage.class)
                .GivenIAmAtHomePage()
                .AndCheckingContent()
                .checkContentWebElementsPresent();
    }

    @Test
    @Description("Check home page footer structure")
    public void checkFooterStructure() {
        page.getPage(HomePage.class)
                .GivenIAmAtHomePage()
                .AndCheckingFooter()
                .AndCheckFooterContactUsPresent()
                .AndCheckSocialMediaPresent()
                .AndCheckFaceBookLinkPresent()
                .AndCheckLinkedInLinkPresent()
                .AndCheckSocialMediaSize();
    }
}
