package org.example.lesson14.andersenlab;// Generated by Selenium IDE

import org.example.BaseTest;
import org.example.lesson14.pages.HomePage;
import org.junit.jupiter.api.Test;

public class PageObjectPageStructureTest extends BaseTest {
    @Test
    public void checkPageStructure() {
        page.getPage(HomePage.class)
                .GivenIAmAtHomePage()
                .AndCheckHeaderPresent()
                .AndCheckIntroPresent()
                .AndCheckContentPresent()
                .AndCheckFooterPresent()
                .AndCheckCopyrightPresent();
    }

    @Test
    public void checkHeaderStructure() {
        page.getPage(HomePage.class)
                .GivenIAmAtHomePage()
                .AndCheckingHeader()
                .AndCheckBookACallPresent()
                .AndCheckHeaderMenuPresent();
    }

    @Test
    public void checkContentStructure() {
        page.getPage(HomePage.class)
                .GivenIAmAtHomePage()
                .AndCheckingContent()
                .checkContentWebElementsPresent();
    }

    @Test
    public void checkFooterStructure() {
        page.getPage(HomePage.class)
                .GivenIAmAtHomePage()
                .AndCheckingFooter()
                .AndCheckFooterContactUsPresent()
                .AndCheckSocialMediaPresent()
                .AndCheckFaceBookLinkPresent()
                .AndCheckLinkedInLinkPresent()
                .AndCheckSocialMediaSize();
    }
}
