package org.example.lesson11.automationpractice;// Generated by Selenium IDE

import org.example.BaseTest;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class LoginTest extends BaseTest {

    @Test
    public void login() {
        driver.get("http://automationpractice.com/index.php");
        driver.manage().window().setSize(new Dimension(1264, 662));
        driver.findElement(By.linkText("Sign out")).click();
        driver.findElement(By.linkText("Sign in")).click();
        driver.findElement(By.id("email")).click();
        driver.findElement(By.id("email")).sendKeys("obailodv13@gmail.com");
        driver.findElement(By.id("passwd")).sendKeys("54564217");
        driver.findElement(By.cssSelector("#SubmitLogin > span")).click();
        assertEquals(driver.findElement(By.cssSelector(".account > span")).getText(), "Oleksii Bailo");
    }
}
