package org.example.lesson11.automationpractice;// Generated by Selenium IDE

import org.example.BaseTest;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;

public class RegisterTest extends BaseTest {

    @Test
    public void register() {
        driver.get("http://automationpractice.com/index.php");
        driver.manage().window().setSize(new Dimension(1264, 662));
        driver.findElement(By.linkText("Sign in")).click();
        driver.findElement(By.id("email_create")).click();
        driver.findElement(By.id("email_create")).sendKeys("obailodv13@gmail.com");
        driver.findElement(By.cssSelector("#SubmitCreate > span")).click();
        driver.findElement(By.cssSelector(".radio-inline:nth-child(3) > .top")).click();
        driver.findElement(By.id("customer_firstname")).click();
        driver.findElement(By.id("customer_firstname")).sendKeys("Oleksii");
        driver.findElement(By.id("customer_lastname")).sendKeys("Bailo");
        driver.findElement(By.id("passwd")).sendKeys("54564217");
        driver.findElement(By.id("days")).click();
        {
            WebElement dropdown = driver.findElement(By.id("days"));
            dropdown.findElement(By.xpath("//option[. = 'regexp:6\\s+']")).click();
        }
        driver.findElement(By.id("months")).click();
        {
            WebElement dropdown = driver.findElement(By.id("months"));
            dropdown.findElement(By.xpath("//option[. = 'regexp:February\\s']")).click();
        }
        driver.findElement(By.id("years")).click();
        {
            WebElement dropdown = driver.findElement(By.id("years"));
            dropdown.findElement(By.xpath("//option[. = 'regexp:1989\\s+']")).click();
        }
        driver.findElement(By.id("address1")).click();
        driver.findElement(By.id("address1")).sendKeys("qwer");
        driver.findElement(By.id("city")).click();
        driver.findElement(By.id("city")).sendKeys("qwer");
        driver.findElement(By.id("id_state")).click();
        {
            WebElement dropdown = driver.findElement(By.id("id_state"));
            dropdown.findElement(By.xpath("//option[. = 'Kansas']")).click();
        }
        driver.findElement(By.id("postcode")).click();
        driver.findElement(By.id("postcode")).sendKeys("00000");
        driver.findElement(By.id("other")).click();
        driver.findElement(By.id("other")).sendKeys("213");
        driver.findElement(By.id("phone_mobile")).click();
        driver.findElement(By.id("phone_mobile")).sendKeys("213");
        driver.findElement(By.cssSelector("#submitAccount > span")).click();
    }
}
